import { Navbar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Manflag fittness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full bg-slate-950">
        <main className="w-full bg-slate-950 text-white">
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
